In [4]:
import numpy as np

In [6]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [7]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Identity Matrix(np.eye)

In [24]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
np.random.rand(3,5)

array([[0.58610838, 0.31656129, 0.34606435, 0.36332296, 0.33230595],
       [0.20749028, 0.78447671, 0.75590494, 0.21478481, 0.44539715],
       [0.07482933, 0.10828636, 0.68576613, 0.12246175, 0.35611379]])

In [44]:
arr=np.random.randn(2,4)
arr

array([[-0.70570025,  0.45109048, -1.08997523, -0.82098543],
       [ 2.15238005, -0.2439843 ,  1.28366565,  1.06590571]])

In [80]:
np.random.randint(2,100)

31

In [81]:
np.random.randint(20,56,100)

array([26, 23, 30, 53, 31, 26, 24, 23, 45, 38, 40, 35, 31, 42, 22, 52, 54,
       40, 53, 34, 47, 30, 41, 45, 45, 44, 29, 49, 23, 23, 36, 40, 28, 22,
       32, 39, 43, 53, 43, 25, 45, 31, 42, 30, 38, 38, 24, 26, 22, 25, 49,
       47, 27, 46, 47, 55, 36, 22, 23, 46, 28, 35, 24, 23, 35, 55, 24, 22,
       55, 36, 35, 26, 40, 47, 24, 51, 36, 20, 49, 28, 41, 52, 33, 28, 30,
       46, 41, 52, 29, 25, 41, 48, 41, 28, 38, 28, 35, 32, 39, 54])

In [82]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [83]:
rand_array=np.random.randint(0,10,50)
rand_array

array([2, 4, 7, 6, 1, 2, 5, 4, 5, 8, 5, 0, 5, 2, 2, 0, 2, 4, 0, 6, 9, 1,
       6, 9, 2, 1, 5, 5, 0, 4, 2, 6, 6, 5, 4, 6, 3, 0, 3, 5, 6, 2, 0, 8,
       3, 8, 5, 2, 6, 2])

In [84]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [86]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])