In [ ]:
import numpy as np

In [ ]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [ ]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Identity Matrix(np.eye)

In [ ]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.random.rand(3,5)

array([[0.58610838, 0.31656129, 0.34606435, 0.36332296, 0.33230595],
       [0.20749028, 0.78447671, 0.75590494, 0.21478481, 0.44539715],
       [0.07482933, 0.10828636, 0.68576613, 0.12246175, 0.35611379]])

In [ ]:
arr=np.random.randn(2,4)
arr

array([[ 1.11106527, -0.1045104 , -1.05447076, -1.33817329],
       [ 0.14766332, -0.38246294,  0.81798679,  0.02303636]])

In [ ]:
np.random.randint(2,100)

23

In [ ]:
np.random.randint(20,56,100)

array([37, 37, 44, 47, 42, 42, 25, 53, 38, 34, 25, 42, 47, 26, 51, 49, 55,
       32, 31, 23, 28, 23, 21, 34, 42, 27, 47, 38, 27, 54, 30, 23, 50, 32,
       28, 34, 53, 38, 22, 25, 52, 45, 22, 47, 44, 26, 50, 48, 20, 31, 47,
       36, 37, 30, 27, 49, 26, 54, 52, 49, 26, 38, 41, 29, 48, 39, 31, 25,
       40, 47, 55, 31, 50, 51, 34, 43, 25, 35, 38, 27, 33, 44, 50, 54, 51,
       22, 25, 21, 51, 54, 29, 37, 28, 50, 37, 23, 52, 34, 36, 52])

In [ ]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array=np.random.randint(0,10,50)
rand_array

array([1, 0, 7, 8, 2, 3, 9, 0, 6, 7, 7, 3, 1, 2, 4, 5, 4, 0, 7, 6, 7, 2,
       0, 4, 0, 6, 4, 6, 7, 2, 4, 8, 3, 5, 6, 6, 5, 7, 7, 6, 3, 6, 3, 0,
       1, 6, 7, 0, 9, 0])

In [ ]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.max()

9

In [ ]:
rand_array.argmax()

6

In [ ]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.99950949, 0.81452502, 0.35001137],
       [0.82203878, 0.10552144, 0.27922476]])

In [ ]:
a.T

array([[0.99950949, 0.82203878],
       [0.81452502, 0.10552144],
       [0.35001137, 0.27922476]])

In [ ]:
sample_array=np.arange(10,21)

sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[0]

10

In [ ]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [ ]:
sample_array=np.arange(10,21)


In [ ]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# **Two-Dimensional array**

In [ ]:
import numpy as np

In [ ]:
sample_matrix=np.array([[50,20,1,23],[2,3,4,5],[6,7,8,9]])
sample_matrix

array([[50, 20,  1, 23],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [ ]:
sample_matrix[1,2]

4

In [ ]:
sample_matrix[2,:]

array([6, 7, 8, 9])

In [ ]:
sample_matrix[2]

array([6, 7, 8, 9])

In [ ]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [ 5,  4],
       [ 9,  8]])

# **Selection techniques**

In [ ]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [ ]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
np.std(sample_array)

5.477225575051661

In [ ]:
np.var(sample_array)

30.0

In [ ]:
np.mean(sample_array)

10.0

In [ ]:
np.max(sample_array)

19

In [ ]:
np.min(sample_array)

1

In [ ]:
np.argmax(sample_array)

18

In [ ]:
np.argmin(sample_array)

0

In [ ]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [ ]:
array=np.random.randn(3,4)
array

array([[ 0.53565628,  1.10949467,  0.53908536, -0.93050108],
       [-1.2401294 ,  0.68314163,  0.08460039,  0.89773562],
       [ 0.27699453, -1.09852417, -0.41955939, -0.3025842 ]])

In [ ]:
np.round(array,decimals=2)

array([[ 0.54,  1.11,  0.54, -0.93],
       [-1.24,  0.68,  0.08,  0.9 ],
       [ 0.28, -1.1 , -0.42, -0.3 ]])

In [ ]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

# **Pandas**

In [ ]:
import pandas as pd
import numpy as np

# **Pandas dataframe and indexing**

In [ ]:
sports1=pd.Series([1,2,3,4],index=['cricket', 'football','basketball', 'golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [ ]:
sports1['football']

2

In [ ]:
sports2=pd.Series([11,2,3,4],index=['cricket', 'football','basetball', 'golf'])
sports2

cricket      11
football      2
basetball     3
golf          4
dtype: int64

In [ ]:
sports1+sports2


basetball      NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [ ]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.063500  0.742769  0.736215  0.368981  0.836419
B  0.295368  0.931123  0.804552  0.836974  0.779826
C  0.135389  0.950217  0.754503  0.344983  0.395262
D  0.998982  0.266466  0.535260  0.251683  0.481806
E  0.401809  0.273924  0.959646  0.079579  0.785447
F  0.348676  0.183854  0.493492  0.802560  0.744298
G  0.232688  0.442981  0.549826  0.143675  0.395192
H  0.808250  0.878837  0.671375  0.615594  0.665973

In [ ]:
df1['Score1']

A    0.063500
B    0.295368
C    0.135389
D    0.998982
E    0.401809
F    0.348676
G    0.232688
H    0.808250
Name: Score1, dtype: float64

In [ ]:
df1[['Score1','Score2']]

Score1    Score2
A  0.063500  0.742769
B  0.295368  0.931123
C  0.135389  0.950217
D  0.998982  0.266466
E  0.401809  0.273924
F  0.348676  0.183854
G  0.232688  0.442981
H  0.808250  0.878837

In [ ]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.063500  0.742769  0.736215  0.368981  0.836419  0.806268
B  0.295368  0.931123  0.804552  0.836974  0.779826  1.226491
C  0.135389  0.950217  0.754503  0.344983  0.395262  1.085606
D  0.998982  0.266466  0.535260  0.251683  0.481806  1.265448
E  0.401809  0.273924  0.959646  0.079579  0.785447  0.675733
F  0.348676  0.183854  0.493492  0.802560  0.744298  0.532530
G  0.232688  0.442981  0.549826  0.143675  0.395192  0.675669
H  0.808250  0.878837  0.671375  0.615594  0.665973  1.687087

In [ ]:
df2={'Company':['Microsoft','Google','Facebook','Amazone','Flipkart'],'Salary':['10M','5M','2M','3M','4M'],'Ranking':[1,2,3,4,5]}
df=pd.DataFrame(df2)
df

Company Salary  Ranking
0  Microsoft    10M        1
1     Google     5M        2
2   Facebook     2M        3
3    Amazone     3M        4
4   Flipkart     4M        5

In [ ]:
df["Company"]

0    Microsoft
1       Google
2     Facebook
3      Amazone
4     Flipkart
Name: Company, dtype: object

In [ ]:
df[["Salary","Ranking"]]

Salary  Ranking
0    10M        1
1     5M        2
2     2M        3
3     3M        4
4     4M        5

In [ ]:
df=df.drop("Salary",axis=1)


In [ ]:
df

Company  Ranking
0  Microsoft        1
1     Google        2
2   Facebook        3
3    Amazone        4
4   Flipkart        5

In [ ]:
df.drop(3)

Company  Ranking
0  Microsoft        1
1     Google        2
2   Facebook        3
4   Flipkart        5